paths:
  /Events:
    post:
      tags:
        - Event
      summary: Create a new instance of the model and persist it into the data source.
      operationId: Event.create
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            description: Model instance data
            $ref: '#/definitions/Event'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Event'
      deprecated: false
    put:
      tags:
        - Event
      summary: >-
        Patch an existing model instance or insert a new one into the data
        source.
      operationId: Event.upsert__put_Events
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            description: Model instance data
            $ref: '#/definitions/Event'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Event'
      deprecated: false
    patch:
      tags:
        - Event
      summary: >-
        Patch an existing model instance or insert a new one into the data
        source.
      operationId: Event.upsert__patch_Events
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            description: Model instance data
            $ref: '#/definitions/Event'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Event'
      deprecated: false
    get:
      tags:
        - Event
      summary: Find all instances of the model matched by filter from the data source.
      operationId: Event.find
      parameters:
        - name: filter
          in: query
          description: >-
            Filter defining fields, where, include, order, offset, and limit -
            must be a JSON-encoded string ({"something":"value"})
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: array
            items:
              $ref: '#/definitions/Event'
      deprecated: false
  /Events/replaceOrCreate:
    post:
      tags:
        - Event
      summary: >-
        Replace an existing model instance or insert a new one into the data
        source.
      operationId: Event.replaceOrCreate
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            description: Model instance data
            $ref: '#/definitions/Event'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Event'
      deprecated: false
  /Events/upsertWithWhere:
    post:
      tags:
        - Event
      summary: >-
        Update an existing model instance or insert a new one into the data
        source based on the where criteria.
      operationId: Event.upsertWithWhere
      parameters:
        - name: where
          in: query
          description: Criteria to match model instances
          required: false
          type: string
          format: JSON
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: false
          schema:
            description: An object of model property name/value pairs
            $ref: '#/definitions/Event'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Event'
      deprecated: false
  '/Events/{id}/exists':
    get:
      tags:
        - Event
      summary: Check whether a model instance exists in the data source.
      operationId: 'Event.exists__get_Events_{id}_exists'
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
            properties:
              exists:
                type: boolean
      deprecated: false
  '/Events/{id}':
    head:
      tags:
        - Event
      summary: Check whether a model instance exists in the data source.
      operationId: 'Event.exists__head_Events_{id}'
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
            properties:
              exists:
                type: boolean
      deprecated: false
    get:
      tags:
        - Event
      summary: 'Find a model instance by {{id}} from the data source.'
      operationId: Event.findById
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
        - name: filter
          in: query
          description: >-
            Filter defining fields and include - must be a JSON-encoded string
            ({"something":"value"})
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Event'
      deprecated: false
    delete:
      tags:
        - Event
      summary: 'Delete a model instance by {{id}} from the data source.'
      operationId: Event.deleteById
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
      deprecated: false
    put:
      tags:
        - Event
      summary: >-
        Patch attributes for a model instance and persist it into the data
        source.
      operationId: 'Event.prototype.updateAttributes__put_Events_{id}'
      parameters:
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: false
          schema:
            description: An object of model property name/value pairs
            $ref: '#/definitions/Event'
        - name: id
          in: path
          description: Event id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Event'
      deprecated: false
    patch:
      tags:
        - Event
      summary: >-
        Patch attributes for a model instance and persist it into the data
        source.
      operationId: 'Event.prototype.updateAttributes__patch_Events_{id}'
      parameters:
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: false
          schema:
            description: An object of model property name/value pairs
            $ref: '#/definitions/Event'
        - name: id
          in: path
          description: Event id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Event'
      deprecated: false
  '/Events/{id}/replace':
    post:
      tags:
        - Event
      summary: >-
        Replace attributes for a model instance and persist it into the data
        source.
      operationId: Event.replaceById
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            description: Model instance data
            $ref: '#/definitions/Event'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Event'
      deprecated: false
  /Events/findOne:
    get:
      tags:
        - Event
      summary: Find first instance of the model matched by filter from the data source.
      operationId: Event.findOne
      parameters:
        - name: filter
          in: query
          description: >-
            Filter defining fields, where, include, order, offset, and limit -
            must be a JSON-encoded string ({"something":"value"})
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Event'
      deprecated: false
  /Events/update:
    post:
      tags:
        - Event
      summary: 'Update instances of the model matched by {{where}} from the data source.'
      operationId: Event.updateAll
      parameters:
        - name: where
          in: query
          description: Criteria to match model instances
          required: false
          type: string
          format: JSON
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: false
          schema:
            description: An object of model property name/value pairs
            $ref: '#/definitions/Event'
      responses:
        '200':
          description: Request was successful
          schema:
            description: Information related to the outcome of the operation
            type: object
            properties:
              count:
                description: The number of instances updated
                type: number
                format: double
      deprecated: false
  /Events/count:
    get:
      tags:
        - Event
      summary: Count instances of the model matched by where from the data source.
      operationId: Event.count
      parameters:
        - name: where
          in: query
          description: Criteria to match model instances
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
            properties:
              count:
                type: number
                format: double
      deprecated: false
definitions:
  Event:
    properties:
      Name:
        type: string
      EventId:
        type: string
      Payload:
        type: object
    required:
      - Name
      - EventId
      - Payload
    additionalProperties: false
  x-any:
    properties: {}
basePath: /api
swagger: '2.0'
info:
  x-ibm-name: onboarding-event-api
  version: 1.0.0
  title: onboarding-event-api
schemes:
  - https
host: $(catalog.host)
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
  clientSecretHeader:
    in: header
    name: X-IBM-Client-Secret
    type: apiKey
security:
  - clientIdHeader: []
    clientSecretHeader: []
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  catalogs:
    apic-dev:
      properties:
        runtime-url: $(TARGET_URL)
    sb:
      properties:
        runtime-url: 'https://onboarding-event-api.mybluemix.net'
        invoke-tls-profile: 'client:Loopback-client'
  assembly:
    execute:
      - invoke:
          target-url: $(runtime-url)$(request.path)$(request.search)
          tls-profile: $(invoke-tls-profile)
  properties:
    runtime-url:
      value: ''
      description: ''
      encoded: false
    invoke-tls-profile:
      value: ''
      description: ''
      encoded: false
